FROM centos:7

#Installing HAProxy for loadbalancing
RUN yum install haproxy &&\
    cp haproxy.cfg haproxy.cfg.original &&\
    firewall-cmd --zone=public --add-port=80/tcp --permanent &&\
    firewall-cmd --reload &&\
    systemctl enable haproxy

CMD systemctl start haproxy
